#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtruyentranh.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuangCao")]
	public partial class QuangCaodbContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTinTuc(TinTuc instance);
    partial void UpdateTinTuc(TinTuc instance);
    partial void DeleteTinTuc(TinTuc instance);
    #endregion
		
		public QuangCaodbContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuangCaoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuangCaodbContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuangCaodbContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuangCaodbContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuangCaodbContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TinTuc> TinTucs
		{
			get
			{
				return this.GetTable<TinTuc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuc")]
	public partial class TinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTinTuc;
		
		private string _TieuDe;
		
		private string _MoDau;
		
		private string _Nguon;
		
		private string _TacGia;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
		private string _HinhAnh;
		
		private string _HinhAnh2;
		
		private string _HinhAnh3;
		
		private string _NoiDung;
		
		private string _NoiDung2;
		
		private string _NoiDung3;
		
		private string _NoiDung4;
		
		private string _ChuThich;
		
		private string _ChuThich2;
		
		private string _ChuThich3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinTucChanging(int value);
    partial void OnMaTinTucChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnMoDauChanging(string value);
    partial void OnMoDauChanged();
    partial void OnNguonChanging(string value);
    partial void OnNguonChanged();
    partial void OnTacGiaChanging(string value);
    partial void OnTacGiaChanged();
    partial void OnThoiGianChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnHinhAnh2Changing(string value);
    partial void OnHinhAnh2Changed();
    partial void OnHinhAnh3Changing(string value);
    partial void OnHinhAnh3Changed();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNoiDung2Changing(string value);
    partial void OnNoiDung2Changed();
    partial void OnNoiDung3Changing(string value);
    partial void OnNoiDung3Changed();
    partial void OnNoiDung4Changing(string value);
    partial void OnNoiDung4Changed();
    partial void OnChuThichChanging(string value);
    partial void OnChuThichChanged();
    partial void OnChuThich2Changing(string value);
    partial void OnChuThich2Changed();
    partial void OnChuThich3Changing(string value);
    partial void OnChuThich3Changed();
    #endregion
		
		public TinTuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinTuc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTinTuc
		{
			get
			{
				return this._MaTinTuc;
			}
			set
			{
				if ((this._MaTinTuc != value))
				{
					this.OnMaTinTucChanging(value);
					this.SendPropertyChanging();
					this._MaTinTuc = value;
					this.SendPropertyChanged("MaTinTuc");
					this.OnMaTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(250)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoDau", DbType="NVarChar(250)")]
		public string MoDau
		{
			get
			{
				return this._MoDau;
			}
			set
			{
				if ((this._MoDau != value))
				{
					this.OnMoDauChanging(value);
					this.SendPropertyChanging();
					this._MoDau = value;
					this.SendPropertyChanged("MoDau");
					this.OnMoDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguon", DbType="NVarChar(250)")]
		public string Nguon
		{
			get
			{
				return this._Nguon;
			}
			set
			{
				if ((this._Nguon != value))
				{
					this.OnNguonChanging(value);
					this.SendPropertyChanging();
					this._Nguon = value;
					this.SendPropertyChanged("Nguon");
					this.OnNguonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TacGia", DbType="NVarChar(250)")]
		public string TacGia
		{
			get
			{
				return this._TacGia;
			}
			set
			{
				if ((this._TacGia != value))
				{
					this.OnTacGiaChanging(value);
					this.SendPropertyChanging();
					this._TacGia = value;
					this.SendPropertyChanged("TacGia");
					this.OnTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh2", DbType="VarChar(50)")]
		public string HinhAnh2
		{
			get
			{
				return this._HinhAnh2;
			}
			set
			{
				if ((this._HinhAnh2 != value))
				{
					this.OnHinhAnh2Changing(value);
					this.SendPropertyChanging();
					this._HinhAnh2 = value;
					this.SendPropertyChanged("HinhAnh2");
					this.OnHinhAnh2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh3", DbType="VarChar(50)")]
		public string HinhAnh3
		{
			get
			{
				return this._HinhAnh3;
			}
			set
			{
				if ((this._HinhAnh3 != value))
				{
					this.OnHinhAnh3Changing(value);
					this.SendPropertyChanging();
					this._HinhAnh3 = value;
					this.SendPropertyChanged("HinhAnh3");
					this.OnHinhAnh3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung2", DbType="NVarChar(MAX)")]
		public string NoiDung2
		{
			get
			{
				return this._NoiDung2;
			}
			set
			{
				if ((this._NoiDung2 != value))
				{
					this.OnNoiDung2Changing(value);
					this.SendPropertyChanging();
					this._NoiDung2 = value;
					this.SendPropertyChanged("NoiDung2");
					this.OnNoiDung2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung3", DbType="NVarChar(MAX)")]
		public string NoiDung3
		{
			get
			{
				return this._NoiDung3;
			}
			set
			{
				if ((this._NoiDung3 != value))
				{
					this.OnNoiDung3Changing(value);
					this.SendPropertyChanging();
					this._NoiDung3 = value;
					this.SendPropertyChanged("NoiDung3");
					this.OnNoiDung3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung4", DbType="NVarChar(MAX)")]
		public string NoiDung4
		{
			get
			{
				return this._NoiDung4;
			}
			set
			{
				if ((this._NoiDung4 != value))
				{
					this.OnNoiDung4Changing(value);
					this.SendPropertyChanging();
					this._NoiDung4 = value;
					this.SendPropertyChanged("NoiDung4");
					this.OnNoiDung4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuThich", DbType="NVarChar(250)")]
		public string ChuThich
		{
			get
			{
				return this._ChuThich;
			}
			set
			{
				if ((this._ChuThich != value))
				{
					this.OnChuThichChanging(value);
					this.SendPropertyChanging();
					this._ChuThich = value;
					this.SendPropertyChanged("ChuThich");
					this.OnChuThichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuThich2", DbType="NVarChar(250)")]
		public string ChuThich2
		{
			get
			{
				return this._ChuThich2;
			}
			set
			{
				if ((this._ChuThich2 != value))
				{
					this.OnChuThich2Changing(value);
					this.SendPropertyChanging();
					this._ChuThich2 = value;
					this.SendPropertyChanged("ChuThich2");
					this.OnChuThich2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuThich3", DbType="NVarChar(250)")]
		public string ChuThich3
		{
			get
			{
				return this._ChuThich3;
			}
			set
			{
				if ((this._ChuThich3 != value))
				{
					this.OnChuThich3Changing(value);
					this.SendPropertyChanging();
					this._ChuThich3 = value;
					this.SendPropertyChanged("ChuThich3");
					this.OnChuThich3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
